### PR TITLE
Latest github actions

### PR DESCRIPTION
**Pull request by kevmoo**
Closes #787
Closes #788

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by kevmoo** [comment]
The failure is an existing one. we should land anyway, me thinks

**Comment by domesticmouse** [comment]
That failing test will have to be fixed before Dart 3.

**Review by domesticmouse — APPROVED** [review]

**Comment by kevmoo** [comment]
Indeed!

**Pull request merged**
