### PR TITLE
Fix unknown enum values in map

### LINKED ISSUE #538: Unknown enum values in map
Hello,

Right now, if we have some protobuf definition like this:

```protobuf
enum Value {
    VALUE_INVALID = 0;
    VALUE_A = 1;
    VALUE_B = 2;
}

message Message {
    map<string, Value> values = 1;
}
```

The protobuf library will parse it correctly.
But now let's suppose we add another value to the enum. 

```protobuf
enum Value {
    VALUE_INVALID = 0;
    VALUE_A = 1;
    VALUE_B = 2;
    VALUE_C = 3;
}

message Message {
    map<string, Value> values = 1;
}
```
Clients generated with the first version (without `VALUE_C`) crashes when parsing a message containing this new value.
And we end up with "DATA_LOSS" when using the grpc lib.

Reading the spec and to match what is happening for enum values outside of maps, I think we should use the default value when we find some unknown enum value in a map. Or we could do the same as what the library is currently doing for lists => skip the value.  

This might be related to #508 and #536 but is also happening without using null safety.

### PR DESCRIPTION
**Pull request by graphman65**
Fix #538 and #508.

### CODE REVIEW

**Comment by graphman65** [comment]
@googlebot I signed it!

**Comment by osa1** [comment]
Thanks for the PR @graphman65. Before reviewing this PR could you please update your branch with `master` and fix/revert formatting changes? This patch will be much smaller and easier to review with formatting changes fixed/reverted. You can run `dart format protobuf; dart format protoc_plugin` at the top level to fix formatting.

**Comment by osa1** [comment]
@graphman65 before making any changes see https://github.com/google/protobuf.dart/issues/538#issuecomment-1107538727 first. If this implements the idea described in your original message in #538 (I can't really tell, diff seems to have unrelated changes) then it's not doing the right thing.

**Review by osa1 — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by osa1** [comment]
Closing due to inactivity. @graphman65 please feel free to reopen if you want to work on this.

**Pull request closed without merging**
