### PR TITLE
Convert null keys and values to default when parsing map entries

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes: https://github.com/google/protobuf.dart/issues/508

### CODE REVIEW

**Comment by kevmoo** [comment]
@mit-mit – who are the "owners" here? @mraleph ?

**Comment by mitenko** [comment]
Can this merge please be expedited?

We are hitting the DATA_LOSS issue parsing header information from protos built with our C# server.

**Comment by mraleph** [comment]
LGTM, though I can't really review it because I am not an owner of the repo.

**Review by mraleph — APPROVED** [review]

**Comment by mraleph** [comment]
@sigurdm would you mind merging and publishing a new version?

**Pull request merged**
